const permisosAgrupados = {
    CLIENTES: [
      { name: 'Agregar Clientes', permiso: 'addcl' },
      { name: 'Ver Clientes', permiso: 'viewcl' },
      { name: 'Archivar Clientes', permiso: 'archcl' },
      { name: 'Editar Clientes', permiso: 'editcl' },
    ],
    PRODUCTOS: [
      { name: 'Agregar Productos', permiso: 'addpr' },
      { name: 'Ver Productos', permiso: 'viewpr' },
      { name: 'Archivar Productos', permiso: 'archpr' },
      { name: 'Editar Productos', permiso: 'edirpr' },
    ],
    CREDITOS: [
      { name: 'Agregar Créditos', permiso: 'addpcr' },
      { name: 'Ver Créditos', permiso: 'viewcr' },
      { name: 'Archivar Créditos', permiso: 'archcr' },
      { name: 'Editar Créditos', permiso: 'edircr' },
      { name: 'Anular Créditos', permiso: 'nullcr' },
      { name: 'Renovar Créditos', permiso: 'mknovcr' },
    ],
    CAJA: [
      { name: 'Agregar Ingresos', permiso: 'addin' },
      { name: 'Agregar Egresos', permiso: 'addeg' },
      { name: 'Autorizar', permiso: 'autorize' },
      { name: 'Ver Caja', permiso: 'viewcj' },
      { name: 'Bloquear Caja', permiso: 'bloqcj' },
      { name: 'Cerrar Caja', permiso: 'cerrarcj' },
      { name: 'Anular Abonos', permiso: 'nullab' },
    ],
    REPORTES: [
      { name: 'Ver Estado de Cuenta', permiso: 'viewStatusAccount' },
      { name: 'Ver Créditos', permiso: 'viewCredits' },
      { name: 'Ver Ingresos/Egresos', permiso: 'viewInEg' },
      { name: 'Ver Utilidad', permiso: 'viewUtility' },
    ],
    GENERAL: [
      { name: 'Ver Config Créditos', permiso: 'viewConfigCredits' },
      { name: 'Editar Config Créditos', permiso: 'editConfigCredits' },
      { name: 'Ver Config Rutas', permiso: 'viewRutaConfig' },
      { name: 'Editar Config Rutas', permiso: 'editRutaConfig' },
      { name: 'Ver Config Caja', permiso: 'viewConfigCaja' },
      { name: 'Editar Config Caja', permiso: 'editConfigCaja' },
      { name: 'Ver Config Laboral', permiso: 'viewLaboral' },
      { name: 'Agregar Config Laboral', permiso: 'addLaboral' },
      { name: 'Eliminar Config Laboral', permiso: 'deleteLaboral' },
      { name: 'Ver Categorías Ingreso', permiso: 'viewConfigIn' },
      { name: 'Agregar Cat. Ingreso', permiso: 'addConfigInCat' },
      { name: 'Editar Cat. Ingreso', permiso: 'editConfigInCat' },
      { name: 'Archivar Cat. Ingreso', permiso: 'archConfigInCat' },
      { name: 'Ver Categorías Egreso', permiso: 'viewConfigEg' },
      { name: 'Agregar Cat. Egreso', permiso: 'addConfigEgCat' },
      { name: 'Editar Cat. Egreso', permiso: 'editConfigEgCat' },
      { name: 'Archivar Cat. Egreso', permiso: 'archConfigEgCat' },
      { name: 'Ver Config Buró', permiso: 'viewConfigBuro' },
      { name: 'Editar Config Buró', permiso: 'editConfigBuro' },
    ],
    EMPRESA: [
      { name: 'Ver Datos Empresa', permiso: 'viewEmpresaData' },
      { name: 'Editar Datos Empresa', permiso: 'editEmpresaData' },
    ],
    OFICINAS: [
      { name: 'Agregar Oficina', permiso: 'addof' },
      { name: 'Ver Oficinas', permiso: 'viewof' },
      { name: 'Editar Oficina', permiso: 'editof' },
      { name: 'Eliminar Oficina', permiso: 'delof' },
    ],
    RUTAS: [
      { name: 'Agregar Ruta', permiso: 'addrut' },
      { name: 'Ver Rutas', permiso: 'viewrut' },
      { name: 'Editar Ruta', permiso: 'editrut' },
      { name: 'Eliminar Ruta', permiso: 'delrut' },
    ],
    TRASLADOS: [
      { name: 'Ver Traslados Ruta', permiso: 'viewRutaTr' },
      { name: 'Crear Traslado Ruta', permiso: 'mkRutaTr' },
      { name: 'Ver Traslados Cliente', permiso: 'viewClTr' },
      { name: 'Crear Traslado Cliente', permiso: 'mkClTr' },
      { name: 'Ver Traslados Dinero', permiso: 'viewMoneyTr' },
      { name: 'Crear Traslado Dinero', permiso: 'mkMoneyTr' },
    ],
    VEHICULOS: [
      { name: 'Ver Vehículos', permiso: 'viewVh' },
      { name: 'Agregar Vehículo', permiso: 'addVh' },
      { name: 'Editar Vehículo', permiso: 'editVh' },
      { name: 'Eliminar Vehículo', permiso: 'delVh' },
    ],
    PERMISOS: [
      { name: 'Agregar Permiso', permiso: 'addperm' },
      { name: 'Editar Permiso', permiso: 'editperm' },
      { name: 'Ver Permisos', permiso: 'viewperm' },
      { name: 'Eliminar Permiso', permiso: 'delperm' },
    ],
    USUARIOS: [
      { name: 'Agregar Usuario', permiso: 'addus' },
      { name: 'Ver Usuarios', permiso: 'viewus' },
      { name: 'Editar Usuario', permiso: 'editus' },
      { name: 'Archivar Usuario', permiso: 'archus' },
    ]
};

export default permisosAgrupados